<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Chaman-Pc" failures="2" tests="11" name="Test" time="45.459" errors="0" timestamp="2024-09-29T08:44:36 IST">
  <testcase classname="TestCase.Login" name="TestCase1" time="0.74"/>
  <testcase classname="TestCase.Login" name="TestCase2" time="2.632"/>
  <testcase classname="TestCase.Login" name="TestCase3" time="0.715"/>
  <testcase classname="TestCase.Login" name="TestCase4" time="0.524"/>
  <testcase classname="TestCase.Login" name="TestCase5" time="0.63"/>
  <testcase classname="TestCase.Login" name="TestCase6" time="0.681"/>
  <testcase classname="TestCase.Login" name="TestCase7" time="5.748"/>
  <testcase classname="TestCase.Login" name="TestCase8" time="0.622"/>
  <testcase classname="TestCase.Login" name="TestCase9" time="0.681"/>
  <testcase classname="TestCase.Product" name="TestCase1" time="2.739">
    <failure type="java.lang.AssertionError" message="expected [Product] but found []">
      <![CDATA[java.lang.AssertionError: expected [Product] but found []
at TestCase.Product.TestCase1(Product.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TestCase1 -->
  <testcase classname="TestCase.Product" name="TestCase2" time="4.036">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at TestCase.Product.TestCase2(Product.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TestCase2 -->
</testsuite> <!-- Test -->
